services:
  fastapi_server:
    build: .
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yuppie
